# Generated by Django 5.0.6 on 2024-06-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpic',
            table='userpictures',
        ),
    ]
