# Generated by Django 5.0.6 on 2024-06-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userpic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpic',
            name='image',
            field=models.ImageField(upload_to='images/user/%Y/%m/%d/'),
        ),
    ]
