# Generated by Django 5.0.6 on 2024-06-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardpage', '0003_alter_projects_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='d0',
            field=models.BooleanField(default=False),
        ),
    ]
