# Generated by Django 5.0.6 on 2024-06-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardpage', '0004_projects_d0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='d0',
            new_name='do',
        ),
    ]
