# Generated by Django 5.0.6 on 2024-06-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardpage', '0007_taskusers_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskusers',
            name='alarm',
        ),
        migrations.AddField(
            model_name='taskusers',
            name='alarm_d',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskusers',
            name='alarm_t',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
