# Generated by Django 5.0.6 on 2024-06-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardpage', '0008_remove_taskusers_alarm_taskusers_alarm_d_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='Projects',
        ),
        migrations.AlterModelTable(
            name='taskusers',
            table='Tasks',
        ),
    ]
