# Generated by Django 5.0.6 on 2024-06-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardpage', '0009_alter_projects_table_alter_taskusers_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskusers',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='parsa'),
        ),
    ]
