# Generated by Django 5.0.6 on 2024-06-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardpage', '0010_alter_taskusers_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskusers',
            name='description',
            field=models.TextField(blank=True, db_column='parsa', null=True),
        ),
    ]
